classDiagram
  direction LR
  namespace core {
    class Type {
      <<Enumeration>>
      Int
      String
      Float
      Enum
    }

    class Cvar {
      <<Abstract>>
      +string name
      +string description
      Type getType()
      parse(string)*
    }

    class Store {
      +T value
      +T pending
      +T default

      -validateCallbacks
      -changeCallbacks
    }

    class Var {
      Store store
    }

    class EnumVar {
      Store store

      Entry[] options
    }

    class Entry {
      +T value
      +string name
      +string description
    }
  }
  Cvar <|-- Var
  Cvar <|-- EnumVar
  Cvar <.. Type

  Var <.. Store
  EnumVar <.. Store
  EnumVar <.. Entry

  %% namespace engine {
  %%   class CvarUi {

  %%   }
  %% }
