#import "lib/manual.typ": head-link

= Profiling <profiling>

Along with support for the Tracy profiler through the
#link(<profiled_opt>, `VN_PROFILED`) option, Vulcanite includes a built-in
profiler for measuring time taken for each section in a tree.

The functions `pushSection`, `popSection`, and `siblingSection` are used to
declare the layout of the tree, and should be placed before/after each major
area. See @section_cpp for an example of tree creation.

#grid(
  columns: 2,
  [#figure(
    ```cpp
    pushSection("My First Section");
      pushSection("A Subsection");
      popSection();
    siblingSection("My Second Section");
      pushSection("Another Subsection");
      popSection();
    popSection();
    ```,
    caption: [C++ code to generate @section_tree's tree],
  ) <section_cpp>],
  [#figure(
    [
      #set align(left)
      - Root
        - My First Section
          - A Subsection
        - My Second Section
          - Another Subsection
    ],
    caption: [Tree generated by @section_cpp],
  ) <section_tree>],
)

== Benchmarks

Benchmarks are performed on the `structure.glb` scene with vsync set to
`LowLatency` and validation layers disabled. These are not at all scientific,e
but provide a rough overview of performance over time.

#let bench(ver, gpu, cpu, fps) = {
  (ver, [#str(gpu)ms], [#str(cpu)ms], [#str(fps)FPS])
}

#figure(
  table(
    columns: (auto, auto, auto, auto),
    table.header([Version], [GPU Wait], [CPU Render], [Framerate]),

    ..bench([V1], 0.27, 0.13, 2300),
    ..bench(head-link(<bindless_vtx>), 0.21, 0.11, 2800),
    ..bench(head-link(<pack_uvs>), 0.19, 0.11, 2900),
    ..bench([Bindless Indexes], 0.20, 0.11, 2800),
    ..bench([Bindless Samplers/Cache Address], 0.20, 0.11, 2900),
    ..bench([Bindless Textures], 0.20, 0.13, 2800),
    ..bench([Frustum Culling], 0.13, 0.14, 3300),
    ..bench(head-link(<true_bindless>), 0.13, 0.14, 3400),
    ..bench(head-link(<indirect>), 0.14, 0.13, 3300),
  ),
  caption: [Benchmarks, and the changes made for them],
)


=== Changes Made

// TODO: Link to this section from the table
==== Bindless Vertices <bindless_vtx>
Replace traditional vertex buffers with buffer references, saving significantly
on CPU time.

==== Packed UVs <pack_uvs>

Pack UV into previously unused padding bytes, saving 8 bytes per vertex, saving
a smaller amount on GPU time.

Also accidentally turns the GPU into a speaker with an audible pitch
proportional to the framerate. I can only guess it's equal to FPS and in the
same camp as "I accidentally made an antenna from my cable"

==== True Bindless Vertices <true_bindless>

Use buffers for vertices rather than RawBufferLoads

==== Indirect Draw <indirect>

Batch all drawcalls into one large buffer and drawcall. This is not GPU-driven
yet as culling is still performed on the CPU.
